import { Provider } from "@/components/provider";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="min-h-[100dvh] scroll-smooth antialiased">
				<Provider>{children}</Provider>
			</body>
		</html>
	);
}
